### ISSUE TITLE
Error when using ICNet model

### ISSUE THREAD

**Issue by htadashi** [hellochick/semantic-segmentation-tensorflow#10]
Hi! 

First of all, thanks for sharing your very helpful code. 
Following the _README.md_, I have downloaded _icnet.npy_ from Google Drive link to the _model/cityscapes_ folder. 

However, when I run 
```
python inference.py --img-path input/outdoor_1.png --model icnet
```
the following error happens: 

```
Traceback (most recent call last):
  File "inference.py", line 65, in <module>
    main()
  File "inference.py", line 44, in main
    model = ICNet()
  File "/home/tadashi/ML/semantic-segmentation-tensorflow/model.py", line 907, in __init__
    super().__init__({'data': self.img_tf}, num_classes, is_training)
TypeError: super() takes at least 1 argument (0 given)
```

**Comment by LinRui9531** [comment]
Did you deal with this error? I also have this error.

**Comment by mgei** [comment]
Workaround in Python 2 change in `model.py` line 907 to

```
super(ICNet, self).__init__({'data': self.img_tf}, num_classes, is_training)
```

See also https://stackoverflow.com/questions/38963018/typeerror-super-takes-at-least-1-argument-0-given-error-is-specific-to-any
